
export const radioData = [
  { value: 1, label: '男' },
  { value: 0, label: '女' },
]

export const educationOptions =[
  { value: 0, label: '小学教育' },
  { value: 1, label: '初中教育' },
  { value: 2, label: '高中教育' },
  { value: 3, label: '中等职业教育' },
  { value: 4, label: '高等职业教育' },
  { value: 5, label: '大学本科' },
  { value: 6, label: '硕士研究生教育' },
  { value: 7, label: '博士研究生教育' },
]

export const nativePlace = [
  { value: 11, label: "北京" },
  { value: 12, label: "天津" },
  { value: 13, label: "河北" },
  { value: 14, label: "山西" },
  { value: 15, label: "內蒙古" },
  { value: 21, label: "辽宁" },
  { value: 22, label: "吉林" },
  { value: 23, label: "黑龙江" },
  { value: 31, label: "上海" },
  { value: 32, label: "江苏" },
  { value: 33, label: "浙江" },
  { value: 34, label: "安徽" },
  { value: 35, label: "福建" },
  { value: 36, label: "江西" },
  { value: 37, label: "山东" },
  { value: 41, label: "河南" },
  { value: 42, label: "湖北" },
  { value: 43, label: "湖南" },
  { value: 44, label: "广东" },
  { value: 45, label: "广西" },
  { value: 46, label: "海南" },
  { value: 50, label: "重庆" },
  { value: 51, label: "四川" },
  { value: 52, label: "贵州" },
  { value: 53, label: "云南" },
  { value: 54, label: "西藏" },
  { value: 61, label: "陕西" },
  { value: 62, label: "甘肃" },
  { value: 63, label: "青海" },
  { value: 64, label: "宁夏" },
  { value: 65, label: "新疆" },
  { value: 71, label: "台湾" },
  { value: 81, label: "香港" },
  { value: 82, label: "澳门" },
  { value: 91, label: "国外" },
]